server:
  port: 8089
  servlet:
    context-path: /cms-admin
debug: false
spring:
  application:
    name: menu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/food?useUnicode=true&characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: Mysql1234!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password: redismima1234
    pool: 
      max-active: 100
      max-wait: -1
      max-idle: 20
      min-idle: 10
    timeout: 2000
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9300
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dliberty.cms.dao.entity
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: Bearer 
#BASE_PATH: /export/static/file
oss:
  endpoint: 
  accessKeyId: 
  accessKeySecret: 
  bucketName: 
app: 
  weixin: 
    appid: 
    secret: 

logging:
  level:
    root: info