server:
  port: 8088
  servlet:
    context-path: /cms
debug: false
spring:
  datasource:
    url: jdbc:mysql://172.17.20.116:30339/food?useUnicode=true&characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: root
    password: qwerty123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: atai-testing-0:6379
    port: 6379
    password: redismima1234
    timeout: 2000
    jedis:
      pool:
        max-idle: 100
        min-idle: 10
        max-wait:
  data:
    elasticsearch:
      cluster-name: eck
      cluster-nodes: 172.17.20.116:31920

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dliberty.cms.dao.entity
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400
  tokenHead: Bearer
BASE_PATH: /export/static/file
oss:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
app:
  weixin:
    appid:
    secret: 
