name: publish-docker

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build And Push Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          mvn -B clean package -pl cms-menu -am -D maven.test.skip=true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: chj9/cms-menu
          tags: latest
          registry: docker.io
          dockerfile: docker/Dockerfile_menu





